name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Needed for committing version changes
  actions: write   # Needed for uploading artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Increment PATCH version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Read current version from build.gradle
          CURRENT_VERSION=$(grep '^version = ' build.gradle | sed "s/version = '//;s/'//")
          # Split into MAJOR.MINOR.PATCH
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          # Increment PATCH
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          # Update build.gradle
          sed -i "s/version = '$CURRENT_VERSION'/version = '$NEW_VERSION'/" build.gradle
          # Generate TritonTechCore.json
          ./gradlew generateVendorJson
          # Commit the changes
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add --force build.gradle TritonTechCore.json
          git commit -m "Bump version to $NEW_VERSION and update TritonTechCore.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test
        run: |
          ./gradlew build --stacktrace
          ./gradlew publishToMavenLocal

      - name: List build directory
        run: ls -R build/libs/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test/
          retention-days: 7

      - name: Upload JAR artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: build/libs/*.jar
          retention-days: 7

      - name: Upload vendor JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vendor-json
          path: TritonTechCore.json
          retention-days: 7